name: Publish to Chocolatey

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push to Chocolatey
        run: choco push chocolatey/tradicted-trading-journal.1.0.0.nupkg --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCOLATEY_API_KEY }}
